language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - cp README.md README.rst
  - pip install cython pytest

install:
  - pip install -e .

script:
  - bash examples/test.sh
  - methplotlib --example > extra_script.sh; bash extra_script.sh
  - py.test tests/

notifications:
  email: false
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/4b1c45cea6826ce475c2
